

# About -------------------------------------------------------------------

# Function Name: plotResults

# Author: Justin Pretorius

# GitHub: https://github.com/jdpretorius123

# LinkedIn: https://www.linkedin.com/in/justin-pretorius 

# -------------------------------------------------------------------------


# Background --------------------------------------------------------------

# This function plots the data for many prospective cohort studies where the 

# study participants have been misclassified with regard to their exposure status. 

# The impact of this misclassification is calculated as a difference relative to 

# the outcomes for these studies had the misclassification never occurred. The 

# following measures of association are used to capture the impact of non-differential 

# misclassification on the results of each simulated study: Risk Difference, Risk 

# Ratio, and Odds Ratio. Only one measure of association, specified through parameter, 

# is graphed with a value, and an average value, from all the simulated studies. Each 

# measure of association was calculated and is plotted under the same sensitivity 

# level and various specificity levels. 

# -------------------------------------------------------------------------


# Parameters --------------------------------------------------------------

# All parameters are named using the following notation:

# 1. If the parameter is one word, then the entire parameter is lowercase.
# 2. If the parameter is two words, then the entire parameter is lowercase,
#    and the first word is separated from the second word by a period.

# -------------------------------------------------------------------------


# Parameter Definitions ---------------------------------------------------

# outcome.data: input matrix containing the differences between the true values 
#               and the observed values for the several measures of association 
#               ( risk difference, risk ratio, and odds ratio ) and the level of 
#               specificity for each simulated study generated by simulateExposure

# sample.size: the study-wide sample size.

# num.studies: the number of studies to simulate.

# measure.association: the measure of association to be plotted; it must be passed 
#                      as a character with one of the following values: 
#                      'Risk Difference', 'Risk Ratio', 'Odds Ratio'

# -------------------------------------------------------------------------


# Function Space Objects that are Not Returned -----------------------------

# All function space objects that are not returned are named using the following 
# notation:

# 1. If the object name is one word, then the entire name is lowercase.
# 2. If the object name is two or more words, then the first word is lowercase,
#    and the second word is capitalized, and etc.

# -------------------------------------------------------------------------


# Function Space Objects that are Returned --------------------------------

# All function space objects that are returned are named using the following 
# notation:

# 1. All object names adhere to CamelCase notation
# 2. If the object name is one word, then the name is capitalized.
# 3. If the object name is two words, then each word is capitalized.

# -------------------------------------------------------------------------


# library( ggplot2 )
# 
# library( tidyverse )
# 
# source( "simulateExposure.r" )
# 
# source( "simulateOutcome.r" )
# 
# set.seed(1)
# 
# prevalence = 0.3
# 
# sample.size = 300
# 
# num.studies = 100
# 
# sensitivity = 1
# 
# specificity = c( 0.5,0.65,0.8,0.95 )
# 
# exposure.data = simulateExposure( prevalence,sample.size,num.studies,sensitivity,specificity )
# 
# risk.exposed = 0.7
# 
# risk.unexposed = 0.3
# 
# outcome.data = simulateOutcome( exposure.data,risk.exposed,risk.unexposed )
# 
# measure.association = "Risk Difference"


plotResults <- function( outcome.data,sample.size,num.studies,measure.association ) {
  
  # stores measure of association to be plotted
  statistic = measure.association
  
  # stores specificity values for each row of input matrix
  specificity = outcome.data[,1]

  # stores differences between true and observed risk differences for each simulated study 
  diffRD = outcome.data[,2]

  # stores differences between true and observed risk ratios for each simulated study
  diffRR = outcome.data[,3]

  # stores differences between true and observed odds ratios for each simulated study
  diffOR = outcome.data[,4]

  # builds data frame containing specificity levels and difference measurements for all 
  #   measures of association
  rawData = data.frame( specificity, diffRD, diffRR, diffOR )

  # coerces specificity variable to factor for dplyr
  rawData$specificity = as.factor( rawData$specificity )
  
  # builds tibble containing specificity levels and average difference measurements 
  #   calculated across all simulated studies for all measures of association
  averages = rawData |>

    group_by( specificity ) |>

    summarise( avgDiffRD = mean( diffRD ),

               avgDiffRR = mean( diffRR ),

               avgDiffOR = mean( diffOR ) )
  
  # builds data frame containing specificity levels and average difference measurements 
  #   calculated across all simulated studies for all measures of association
  averages = data.frame( averages )
  
  # asks if measure of association to be plotted is risk difference
  if ( statistic == "Risk Difference" ) {
    
    # stores data for difference in risk difference for each simulated study
    measureAssociation = rawData$diffRD

    # stores data for average difference in risk difference calculated across all 
    #   simulated studies
    avgAssociation = averages$avgDiffRD
    
  }
  
  # asks if measure of association to be plotted is risk ratio
  if ( statistic == "Risk Ratio" ) {
    
    # stores data for difference in risk ratio for each simulated study
    measureAssociation = rawData$diffRR

    # stores data for average difference in risk ratio calculated across all simulated studies
    avgAssociation = averages$avgDiffRR
    
  }
  
  # asks if measure of association to be plotted is odds ratio
  if ( statistic == "Odds Ratio" ) {
    
    # stores data for difference in odds ratio for each simulated study
    measureAssociation = rawData$diffOR

    # stores data for average difference in odds ratio calculated across all simulated studies
    avgAssociation = averages$avgDiffOR
    
  }
  
  # builds data frame with differences in specified measure of association for each simulated 
  #   study
  plotRawData = data.frame( rawData$specificity, measureAssociation )
  
  # builds data frame with average difference in specified measure of association calculated 
  #   across all simulated studies
  plotAvgData = data.frame( averages$specificity, avgAssociation )

  # builds ggplot with aesthetics
  plottedData = ggplot( data = plotRawData, 
                        
                        aes( x = rawData.specificity, 
                             
                             y = measureAssociation, 
                             
                             colour = rawData.specificity ) ) +
    
    geom_boxplot( show.legend = FALSE ) +
    
    geom_point( size = 4, 
                
                alpha = 0.1, 
                
                show.legend = FALSE ) + 
    
    geom_point( data = plotAvgData, 
                
                aes(x = averages.specificity, 
                    
                    y = avgAssociation, 
                    
                    colour = averages.specificity ), 
                
                size = 10, 
                
                shape = "diamond", 
                
                show.legend = FALSE ) +
    
    ggtitle( paste( "Differences for", 
                    
                    statistic, 
                    
                    "Holding Sensitivity Constant and Varying Specificity", 
                    
                    sep = " " ) ) +
    
    xlab( "Specificity" ) +
    
    ylab( paste( "Differences for", 
                 
                 statistic, 
                 
                 "Across", 
                 
                 num.studies, 
                 
                 "Studies Each With",
                 
                 sample.size,
                 
                 "Samples",
                 
                 sep = " " ) ) +
    
    theme( plot.title = element_text( hjust = 0.5 ),
           
           panel.background = element_rect( fill = NA, colour = "black" ),
           
           panel.grid.minor = element_blank(),
           
           panel.grid.major = element_line( colour = "black" ),
           
           axis.title = element_text( size = 14 ),
           
           axis.text.y = element_text( size = 12 ),
           
           axis.text.x = element_text( size = 12 ) ) +
    
    coord_flip()
  
  return( plottedData )
  
}
