

# About -------------------------------------------------------------------

# Application Name: ExposureError

# Author: Justin Pretorius

# GitHub: https://github.com/jdpretorius123

# LinkedIn: https://www.linkedin.com/in/justin-pretorius 

# -------------------------------------------------------------------------


# Background ------------------------------------------------------------

# These functions build the components for a shiny app that is called at the end of the script. 

# The user input for this shiny app simulates the data for many prospective cohort studies where 

# the study participants have been misclassified with regard to their exposure status. The impact 

# of this misclassification is calculated as a difference relative to the outcomes for these studies 

# had the misclassification never occurred. The following measures of association are used to capture 

# the impact of non-differential misclassification on the results of each simulated study: 

# Risk Difference, Risk Ratio, and Odds Ratio. Only one measure of association, specified through 

# user input, is graphed with a value, and an average value, from all the simulated studies. Each 

# measure of association is calculated and is plotted under one sensitivity level and various 

# specificity levels. 

# -------------------------------------------------------------------------


# Function Parameters -----------------------------------------------------

# All parameters are named using the following notation:

# 1. If the parameter is one word, then the entire parameter is lowercase.
# 2. If the parameter is two words, then the entire parameter is lowercase,
#    and the first word is separated from the second word by a period.

# -------------------------------------------------------------------------


# Parameter Definitions ---------------------------------------------------

# exposure.data: input matrix containing the true positives and negatives, the observed positives and 
#                negatives, the false positives and false negatives resulting from non-differential 
#                misclassification, and the level of specificity for each simulated study generated 
#                by simulateExposure

# outcome.data: input matrix containing the differences between the true values and the observed 
#               values for the several measures of association ( risk difference, risk ratio, and 
#               odds ratio ) and the level of specificity for each simulated study generated by 
#               simulateExposure

# prevalence: the population prevalence of the exposure.

# sample.size: the study-wide sample size.

# num.studies: the number of studies to simulate.

# sensitivity: the constant sensitivity applied to each simulated study; it must be passed as one 
#              floating-point value.

# specificity: the levels of specificity to be applied to each simulated study; it must be passed as 
#              a vector with any number of floating-point values as entries.

# risk.exposed: the risk associated with developing the outcome of interest in the exposed group

# risk.unexposed: the risk associated with developing the outcome of interest in the unexposed group

# measure.association: the measure of association to be plotted; it must be passed as a character 
#                      with one of the following values: 'Risk Difference', 'Risk Ratio', 'Odds Ratio'

# -------------------------------------------------------------------------


# Function Space Objects that are Not Returned -----------------------------

# All function space objects that are not returned are named using the following notation:

# 1. If the object name is one word, then the entire name is lowercase.
# 2. If the object name is two or more words, then the first word is lowercase,
#    and the second word is capitalized, and etc.

# -------------------------------------------------------------------------


# Function Space Objects that are Returned --------------------------------

# All function space objects that are returned are named using the following notation:

# 1. All object names adhere to CamelCase notation
# 2. If the object name is one word, then the name is capitalized.
# 3. If the object name is two words, then each word is capitalized.

# -------------------------------------------------------------------------


source( 'modules/simulateExposure.R' )

source( 'modules/simulateOutcome.R' )

source( 'modules/plotResults.R' )

source( 'modules/characterToNumeric.R' )

library( shiny )

library( tidyverse )

library( ggplot2 )

# creates user interface for the shiny app
ui = fluidPage(
  
  # creates container for importing stylesheet
  tags$head(
    
    tags$link(
      
      rel = "stylesheet",
      
      type = "text/css",
      
      href = "exposureCSS.css"
      
    )
    
  ),
  
  # creates container for applying styles to app title and title image
  div(
    
    id = "ui",
    
    titlePanel(
      
      title = 
        
        div(
          
          id = "title",
          
          img(
            
            id = "DukeEmblem",
            
            src = "DukeSOM.png",
            
            alt = "Duke School of Medicine Emblem",
            
            title = "Duke School of Medicine Emblem"
            
          ),
          
          "Exposure Measurement Error in a Prospective Cohort Study"
          
        ),
      
      windowTitle = "Exposure Measurement Error"
      
    ),
    
    br(),
    br(),
    
    # creates sidebar container for help text and widgets for user interface
    sidebarLayout(
      
      # creates container for applying styles to help text and widgets
      div(
        
        id = "sidebar",
        
        sidebarPanel(
          
          p(
            
            id = "instructions",
            
            "This simulation explores the impact of exposure measurement error on 
            measures of association. This impact is simulated by holding sensitivity 
            constant and varying specificity. For example, a researcher wants to know 
            if the presence of an exposure is associated with cancer development. 
            They have three diagnostic tests to choose from to dichotomize the presence 
            of the exposure in study participants. Each device has a similar sensitivity. 
            However, specificity varies across the devices. Each data point denotes one
            simulated study, and the diamond represents the average value computed across 
            all simulated studies. Data are displayed for each specificity. Please note
            that ",
            
            tags$b( "Sample Size" ),
            
            " is the study-wide sample size, and that specificity needs to be entered as
            comma separated values. When ready, please click ",
            
            tags$b( "Run. " )
            
          ),
          
          br(),
          
          div(
            
            id = "rowOne",
            
            # limits exposure prevalence to decimal between 0 and 1
            numericInput(
              
              inputId = "prevalence",
              
              label = "Exposure Prevalence:",
              
              value = 0.3,
              
              min = 0,
              
              max = 1,
              
              step = 0.01,
              
              width = '75px'
              
            ),
            
            # limits sensitivity to decimal between 0 and 1
            numericInput(
              
              inputId = "sensitivity",
              
              label = "Sensitivity:",
              
              value = 0.9,
              
              min = 0,
              
              max = 1,
              
              step = 0.01,
              
              width = '75px'
              
            ),
            
            textInput(
              
              inputId = "specificity",
              
              label = "Specificity",
              
              placeholder = "Ex: 0.6,0.75,0.9",
              
              width = '150px'
              
            )
            
          ),
          
          div(
            
            id = "rowTwo",
            
            # limits risk.exposed to decimal between 0 and 1
            numericInput(
              
              inputId = "riskExposed",
              
              label = "Risk Exposed:",
              
              value = 0.7,
              
              min = 0,
              
              max = 1,
              
              width = '75px'
              
            ),
            
            # limits risk.unexposed to decimal between 0 and 1
            numericInput(
              
              inputId = "riskUnexposed",
              
              label = "Risk Unexposed:",
              
              value = 0.3,
              
              min = 0,
              
              max = 1,
              
              width = '75px'
              
            ),
            
            # limits sample.size to integer between 250 and 2000
            numericInput(
              
              inputId = "sampleSize",
              
              label = "Sample Size:",
              
              value = 500,
              
              min = 250,
              
              max = 2000,
              
              width = '75px'
              
            )
            
          ),
          
          # limits measure.association parameter to three character value with correct case
          selectInput(
            
            inputId = "measureAssociation",
            
            label = "Measure of Association",
            
            choices = c( 
              
              "Risk Difference",
              
              "Risk Ratio",
              
              "Odds Ratio"
              
            ),
            
            selected = "Risk Difference",
            
            width = '200px'
            
          ),
          
          # creates interactive button to initiate simulation by activating observeEvent
          actionButton(
            
            inputId = "run",
            
            label = "Run"
            
          )
          
        )
        
      ),
      
      # creates main panel container for display of simulation results
      mainPanel(
        
        plotOutput(
          
          outputId = "sim",
          
          height = "725px"
          
        )
        
      )
      
    )
    
  )
  
)

# creates server for shiny app
server = shinyServer( 
  
  function( input,output )
    
  {
    
    # specifies user initiated display of results
    observeEvent(
      
      input$run, {
        
        set.seed(1)
        
        prevalence = input$prevalence
        
        sample.size = input$sampleSize
        
        num.studies = 500
        
        sensitivity = input$sensitivity
        
        character.string = input$specificity
        
        specificity = characterToNumeric( character.string )
        
        risk.exposed = input$riskExposed
        
        risk.unexposed = input$riskUnexposed
        
        measure.association = input$measureAssociation
        
        exposure.data = simulateExposure( prevalence,sample.size,num.studies,sensitivity,specificity )
        
        outcome.data = simulateOutcome( exposure.data,risk.exposed,risk.unexposed )
        
        plot.results = plotResults( outcome.data,sample.size,num.studies,measure.association )
        
        output$sim = renderPlot( plot.results,
                                 
                                 res = 100,
                                 
                                 alt = "A grouped box plot with various levels of specificity on the y-axis
                                 
                                 and average difference between the observed and true measure of association on
                                 
                                 the x-axis." )
        
      }
      
    )
    
  }
  
)

# calls shiny app
shinyApp(ui = ui, server = server)

